name: '522_Group6'
channels:
  - conda-forge
  - defaults
dependencies:
  - ipykernel
  - matplotlib>=3.2.2
  - scikit-learn>=1.0
  - pandas>=1.3.*
  - requests>=2.24.0
  - altair_saver
  - vega_datasets
  - graphviz
  - python-graphviz
  - jinja2y
  - pip
  - lightgbm
  - py-xgboost==1.3.0
  - catboost
  - spacy
  - wikipedia
  - nltk
  - eli5
  - shap
  - seaborn
  - imbalanced-learn
  - pandas-profiling
  - ipywidgets
  - docopt
  - pycountry
  - wordcloud
  - geopandas
  - openpyxl
  - pip:
    - boruta==0.3
    - mglearn
    - psutil>=5.7.2
    - rpy2
